In [3]:
import pandas as pd
import numpy as np

In [4]:
df= pd.DataFrame({
    "job_title": ["Data Scientist", "Data Analyst", "Data Engineer", "Data Scientist", "Data Analyst"],
    "salary": [120000, 80000, 100000, 130000, 85000]     })

df

        job_title  salary
0  Data Scientist  120000
1    Data Analyst   80000
2   Data Engineer  100000
3  Data Scientist  130000
4    Data Analyst   85000

In [6]:
mean_salary = df.groupby("job_title")["salary"].mean().sort_values().to_dict()

In [7]:
df["salary_label"] = df["job_title"].map(mean_salary)
df[["job_title", "salary", "salary_label"]]

        job_title  salary  salary_label
0  Data Scientist  120000      125000.0
1    Data Analyst   80000       82500.0
2   Data Engineer  100000      100000.0
3  Data Scientist  130000      125000.0
4    Data Analyst   85000       82500.0