In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


# Set the random seed for reproducibility
np.random.seed(119)

n_transactions = 1000
genuine_ratio =0.9

n_genuine= int(n_transactions * genuine_ratio)
n_fraudulent = n_transactions - n_genuine

In [15]:
genuine = pd.DataFrame({
    'amount': np.random.normal(loc=500, scale=200, size=n_genuine),
    'gap_minutes': np.random.normal(loc=120, scale=40, size=n_genuine),
    'is_fraud': [0] * n_genuine
})

In [16]:
genuine

         amount  gap_minutes  is_fraud
0    498.497759   117.560664         0
1    740.938553   108.386489         0
2    630.087826   119.720222         0
3    347.387546   168.215102         0
4    392.126343   121.488318         0
..          ...          ...       ...
895  644.330998   182.435320         0
896  527.219433    86.987892         0
897  270.325307    92.802181         0
898  553.262833    79.576053         0
899  452.969770   173.802439         0

[900 rows x 3 columns]

In [17]:
fraud = pd.DataFrame({
    'amount': np.random.normal(loc=2000, scale=500, size=n_fraudulent),
    'gap_minutes': np.random.normal(loc=10, scale=5, size=n_fraudulent),
    'is_fraud': [1] * n_fraudulent  
})

In [18]:
fraud

         amount  gap_minutes  is_fraud
0   2096.202560    13.071199         1
1   1642.731565    14.246493         1
2   2179.227762    11.509900         1
3   2474.419109    12.553478         1
4   1278.865246     9.893619         1
..          ...          ...       ...
95  2752.005161    12.089576         1
96  1330.669056    -2.278083         1
97  2196.595272    15.924713         1
98  2021.542268    14.058664         1
99  1793.438360    11.785588         1

[100 rows x 3 columns]

In [19]:
df = pd.concat([genuine, fraud]).reset_index(drop=True)
df

          amount  gap_minutes  is_fraud
0     498.497759   117.560664         0
1     740.938553   108.386489         0
2     630.087826   119.720222         0
3     347.387546   168.215102         0
4     392.126343   121.488318         0
..           ...          ...       ...
995  2752.005161    12.089576         1
996  1330.669056    -2.278083         1
997  2196.595272    15.924713         1
998  2021.542268    14.058664         1
999  1793.438360    11.785588         1

[1000 rows x 3 columns]

In [20]:
df['is_fraud'].value_counts()

is_fraud
0    900
1    100
Name: count, dtype: int64

In [21]:
df_minority = df[df['is_fraud'] == 1]
df_majority = df[df['is_fraud'] == 0]

In [24]:
from sklearn.utils import resample
df_minority_upsampled= resample(df_minority, replace=True, n_samples=len(df_majority),random_state=92)

In [25]:
df_minority_upsampled.shape

(900, 3)

In [27]:
df_upscaled = pd.concat([df_majority, df_minority_upsampled])
df_upscaled

          amount  gap_minutes  is_fraud
0     498.497759   117.560664         0
1     740.938553   108.386489         0
2     630.087826   119.720222         0
3     347.387546   168.215102         0
4     392.126343   121.488318         0
..           ...          ...       ...
915  1951.146813    14.934573         1
996  1330.669056    -2.278083         1
917  2371.898882    11.833305         1
942  2142.525109     9.308098         1
942  2142.525109     9.308098         1

[1800 rows x 3 columns]